apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: image-resolver-api
spec:
  rules:
  - http:
      paths:
      - path: /api/*
        backend:
          serviceName: image-resolver-api-svc
          servicePort: 8080