apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-resolver-api-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: image-resolver-api
        image: shekhargulati/image-resolver-api
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
        - containerPort: 8080
