apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-resolver-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: image-resolver-api
        image: shekhargulati/image-resolver-api
        resources:
          limits:
            memory: "256Mi"
            cpu: "125m"
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: image-resolver-api-depl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-resolver-api-depl
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
