apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
  labels:
    failure-domain.beta.kubernetes.io/zone: asia-south1-b
spec:
  capacity:
    storage: 20Mi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: k8s-disk
    fsType: ext4
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "task-pv-claim"
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  volumeName: "test-volume"